name: zup_core
description: "Core library for Zup apps and libraries"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.2

dependencies:
  flutter:
    sdk: flutter
  fake_async: ^1.3.1
  clock: ^1.1.1
  flutter_test:
    sdk: flutter
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: ^4.0.0
  golden_toolkit: ^0.15.0
