name: zup_core
description: "Core library for Zup apps and libraries"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  fake_async: ^1.3.1
  clock: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
